import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/common/MainLayout";

export const metadata: Metadata = {
  title: "Startup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
